services:
  - type: web
    name: your-app
    runtime: python
    buildCommand: |
      python -m venv /opt/render/project/src/.venv
      source /opt/render/project/src/.venv/bin/activate
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: |
      source /opt/render/project/src/.venv/bin/activate
      gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 app:app