services:
  - type: web
    name: diabetes-prediction
    runtime: python
    buildCommand: |
      pip install poetry
      poetry install --no-dev
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: PORT
        value: 5000